# Generated by Django 3.2.25 on 2025-03-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250304_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bracelet_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='necklace_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
